train:
  _target_: src.datasets.DigiCamMirflickrDataset
  split: train
  data_dir: ".cache"
  instance_transforms: ${transforms.instance_transforms.train}

test:
  _target_: src.datasets.DigiCamMirflickrDataset
  split: test
  data_dir: ".cache"
  instance_transforms: ${transforms.instance_transforms.inference}
