_target_: src.logger.CometMLWriter
project_name: "lensless-hw5"
workspace: null
run_name: "baseline"
mode: "online"
loss_names: ["loss", "mse_loss", "lpips_loss"]
log_checkpoints: false
id_length: 32
